require("options")
require("plugins")

require("lsp")
require("config.nvim-treesitter")
require("config.clipboard-image")
require("config.hop")
require("config.telescope")
require("config.nvim-dap")
--require("config.conform")
require("config.nvim-cmp")
require("config.luasnip")
require("config.sniprun")
require("plantuml").setup()
require("ibl").setup()
require("keymaps")
require("colorscheme")
